/* Auto-generated by scripts/import-download-aug.mjs — do not edit by hand */
export type ProjectImage = { url: string; room: string };

export interface Project {
  slug: string;
  title: string;
  category: string;
  description: string;
  coverImage: string;
  images: string[];
  gallery: ProjectImage[];
  rooms: string[];
  location?: string;
}

export const ROOM_FILTERS = [
  "Bucătării",
  "Living",
  "Dressing",
  "Dormitoare",
  "Băi",
  "Hol"
] as const;

export const projects: Project[] = [
  {
    "slug": "villa-06",
    "title": "Villa 06",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Villa 06. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/villa-06/01.living.cover.webp",
    "images": [
      "/projects/villa-06/01.living.cover.webp",
      "/projects/villa-06/02.living.img.webp",
      "/projects/villa-06/03.living.img.webp",
      "/projects/villa-06/04.living.img.webp",
      "/projects/villa-06/05.living.img.webp",
      "/projects/villa-06/06.living.img.webp",
      "/projects/villa-06/07.bucatarii.img.webp",
      "/projects/villa-06/08.bucatarii.img.webp",
      "/projects/villa-06/09.bucatarii.img.webp",
      "/projects/villa-06/10.dormitoare.img.webp",
      "/projects/villa-06/11.dormitoare.img.webp",
      "/projects/villa-06/12.dormitoare.img.webp",
      "/projects/villa-06/13.dormitoare.img.webp",
      "/projects/villa-06/14.dormitoare.img.webp",
      "/projects/villa-06/15.dormitoare.img.webp",
      "/projects/villa-06/16.dormitoare.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/villa-06/01.living.cover.webp",
        "room": "Living"
      },
      {
        "url": "/projects/villa-06/02.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/villa-06/03.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/villa-06/04.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/villa-06/05.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/villa-06/06.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/villa-06/07.bucatarii.img.webp",
        "room": "Bucătării"
      },
      {
        "url": "/projects/villa-06/08.bucatarii.img.webp",
        "room": "Bucătării"
      },
      {
        "url": "/projects/villa-06/09.bucatarii.img.webp",
        "room": "Bucătării"
      },
      {
        "url": "/projects/villa-06/10.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-06/11.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-06/12.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-06/13.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-06/14.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-06/15.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-06/16.dormitoare.img.webp",
        "room": "Dormitoare"
      }
    ],
    "rooms": [
      "Living",
      "Bucătării",
      "Dormitoare"
    ]
  },
  {
    "slug": "villa-05",
    "title": "Villa 05",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Villa 05. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/villa-05/01.living.cover.webp",
    "images": [
      "/projects/villa-05/01.living.cover.webp",
      "/projects/villa-05/02.living.img.webp",
      "/projects/villa-05/03.living.img.webp",
      "/projects/villa-05/04.living.img.webp",
      "/projects/villa-05/05.living.img.webp",
      "/projects/villa-05/06.living.img.webp",
      "/projects/villa-05/07.bucatarii.img.webp",
      "/projects/villa-05/08.bucatarii.img.webp",
      "/projects/villa-05/09.bucatarii.img.webp",
      "/projects/villa-05/10.dormitoare.img.webp",
      "/projects/villa-05/11.dormitoare.img.webp",
      "/projects/villa-05/12.dormitoare.img.webp",
      "/projects/villa-05/13.dormitoare.img.webp",
      "/projects/villa-05/14.dormitoare.img.webp",
      "/projects/villa-05/15.bai.img.webp",
      "/projects/villa-05/16.bai.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/villa-05/01.living.cover.webp",
        "room": "Living"
      },
      {
        "url": "/projects/villa-05/02.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/villa-05/03.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/villa-05/04.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/villa-05/05.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/villa-05/06.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/villa-05/07.bucatarii.img.webp",
        "room": "Bucătării"
      },
      {
        "url": "/projects/villa-05/08.bucatarii.img.webp",
        "room": "Bucătării"
      },
      {
        "url": "/projects/villa-05/09.bucatarii.img.webp",
        "room": "Bucătării"
      },
      {
        "url": "/projects/villa-05/10.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-05/11.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-05/12.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-05/13.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-05/14.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-05/15.bai.img.webp",
        "room": "Băi"
      },
      {
        "url": "/projects/villa-05/16.bai.img.webp",
        "room": "Băi"
      }
    ],
    "rooms": [
      "Living",
      "Bucătării",
      "Dormitoare",
      "Băi"
    ]
  },
  {
    "slug": "villa-04",
    "title": "Villa 04",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Villa 04. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/villa-04/01.altele.cover.webp",
    "images": [
      "/projects/villa-04/01.altele.cover.webp",
      "/projects/villa-04/02.altele.img.webp",
      "/projects/villa-04/03.altele.img.webp",
      "/projects/villa-04/04.altele.img.webp",
      "/projects/villa-04/05.altele.img.webp",
      "/projects/villa-04/06.altele.img.webp",
      "/projects/villa-04/07.altele.img.webp",
      "/projects/villa-04/08.altele.img.webp",
      "/projects/villa-04/09.altele.img.webp",
      "/projects/villa-04/10.altele.img.webp",
      "/projects/villa-04/11.altele.img.webp",
      "/projects/villa-04/12.altele.img.webp",
      "/projects/villa-04/13.altele.img.webp",
      "/projects/villa-04/14.altele.img.webp",
      "/projects/villa-04/15.altele.img.webp",
      "/projects/villa-04/16.altele.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/villa-04/01.altele.cover.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-04/02.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-04/03.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-04/04.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-04/05.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-04/06.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-04/07.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-04/08.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-04/09.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-04/10.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-04/11.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-04/12.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-04/13.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-04/14.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-04/15.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-04/16.altele.img.webp",
        "room": "Altele"
      }
    ],
    "rooms": []
  },
  {
    "slug": "apartment-01",
    "title": "Apartment 01",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Apartment 01. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/apartment-01/01.altele.cover.webp",
    "images": [
      "/projects/apartment-01/01.altele.cover.webp",
      "/projects/apartment-01/02.altele.img.webp",
      "/projects/apartment-01/03.altele.img.webp",
      "/projects/apartment-01/04.altele.img.webp",
      "/projects/apartment-01/05.altele.img.webp",
      "/projects/apartment-01/06.altele.img.webp",
      "/projects/apartment-01/07.altele.img.webp",
      "/projects/apartment-01/08.altele.img.webp",
      "/projects/apartment-01/09.altele.img.webp",
      "/projects/apartment-01/10.altele.img.webp",
      "/projects/apartment-01/11.altele.img.webp",
      "/projects/apartment-01/12.altele.img.webp",
      "/projects/apartment-01/13.altele.img.webp",
      "/projects/apartment-01/14.altele.img.webp",
      "/projects/apartment-01/15.altele.img.webp",
      "/projects/apartment-01/16.altele.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/apartment-01/01.altele.cover.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-01/02.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-01/03.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-01/04.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-01/05.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-01/06.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-01/07.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-01/08.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-01/09.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-01/10.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-01/11.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-01/12.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-01/13.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-01/14.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-01/15.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-01/16.altele.img.webp",
        "room": "Altele"
      }
    ],
    "rooms": []
  },
  {
    "slug": "apartment-15",
    "title": "Apartment 15",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Apartment 15. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/apartment-15/01.living.cover.webp",
    "images": [
      "/projects/apartment-15/01.living.cover.webp",
      "/projects/apartment-15/02.living.img.webp",
      "/projects/apartment-15/03.living.img.webp",
      "/projects/apartment-15/04.dormitoare.img.webp",
      "/projects/apartment-15/05.dormitoare.img.webp",
      "/projects/apartment-15/06.dormitoare.img.webp",
      "/projects/apartment-15/07.altele.img.webp",
      "/projects/apartment-15/08.altele.img.webp",
      "/projects/apartment-15/09.altele.img.webp",
      "/projects/apartment-15/10.altele.img.webp",
      "/projects/apartment-15/11.altele.img.webp",
      "/projects/apartment-15/12.bai.img.webp",
      "/projects/apartment-15/13.bai.img.webp",
      "/projects/apartment-15/14.bai.img.webp",
      "/projects/apartment-15/15.hol.img.webp",
      "/projects/apartment-15/16.dressing.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/apartment-15/01.living.cover.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-15/02.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-15/03.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-15/04.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-15/05.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-15/06.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-15/07.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-15/08.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-15/09.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-15/10.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-15/11.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-15/12.bai.img.webp",
        "room": "Băi"
      },
      {
        "url": "/projects/apartment-15/13.bai.img.webp",
        "room": "Băi"
      },
      {
        "url": "/projects/apartment-15/14.bai.img.webp",
        "room": "Băi"
      },
      {
        "url": "/projects/apartment-15/15.hol.img.webp",
        "room": "Hol"
      },
      {
        "url": "/projects/apartment-15/16.dressing.img.webp",
        "room": "Dressing"
      }
    ],
    "rooms": [
      "Living",
      "Dormitoare",
      "Băi",
      "Hol",
      "Dressing"
    ]
  },
  {
    "slug": "apartment-13",
    "title": "Apartment 13",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Apartment 13. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/apartment-13/01.altele.cover.webp",
    "images": [
      "/projects/apartment-13/01.altele.cover.webp",
      "/projects/apartment-13/02.altele.img.webp",
      "/projects/apartment-13/03.altele.img.webp",
      "/projects/apartment-13/04.altele.img.webp",
      "/projects/apartment-13/05.altele.img.webp",
      "/projects/apartment-13/06.altele.img.webp",
      "/projects/apartment-13/07.altele.img.webp",
      "/projects/apartment-13/08.altele.img.webp",
      "/projects/apartment-13/09.altele.img.webp",
      "/projects/apartment-13/10.altele.img.webp",
      "/projects/apartment-13/11.altele.img.webp",
      "/projects/apartment-13/12.altele.img.webp",
      "/projects/apartment-13/13.altele.img.webp",
      "/projects/apartment-13/14.altele.img.webp",
      "/projects/apartment-13/15.altele.img.webp",
      "/projects/apartment-13/16.altele.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/apartment-13/01.altele.cover.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-13/02.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-13/03.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-13/04.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-13/05.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-13/06.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-13/07.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-13/08.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-13/09.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-13/10.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-13/11.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-13/12.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-13/13.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-13/14.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-13/15.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-13/16.altele.img.webp",
        "room": "Altele"
      }
    ],
    "rooms": []
  },
  {
    "slug": "apartment-12",
    "title": "Apartment 12",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Apartment 12. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/apartment-12/01.altele.cover.webp",
    "images": [
      "/projects/apartment-12/01.altele.cover.webp",
      "/projects/apartment-12/02.altele.img.webp",
      "/projects/apartment-12/03.altele.img.webp",
      "/projects/apartment-12/04.altele.img.webp",
      "/projects/apartment-12/05.altele.img.webp",
      "/projects/apartment-12/06.altele.img.webp",
      "/projects/apartment-12/07.altele.img.webp",
      "/projects/apartment-12/08.altele.img.webp",
      "/projects/apartment-12/09.altele.img.webp",
      "/projects/apartment-12/10.altele.img.webp",
      "/projects/apartment-12/11.altele.img.webp",
      "/projects/apartment-12/12.altele.img.webp",
      "/projects/apartment-12/13.altele.img.webp",
      "/projects/apartment-12/14.altele.img.webp",
      "/projects/apartment-12/15.altele.img.webp",
      "/projects/apartment-12/16.altele.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/apartment-12/01.altele.cover.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-12/02.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-12/03.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-12/04.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-12/05.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-12/06.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-12/07.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-12/08.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-12/09.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-12/10.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-12/11.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-12/12.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-12/13.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-12/14.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-12/15.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-12/16.altele.img.webp",
        "room": "Altele"
      }
    ],
    "rooms": []
  },
  {
    "slug": "villa-03",
    "title": "Villa 03",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Villa 03. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/villa-03/01.living.cover.webp",
    "images": [
      "/projects/villa-03/01.living.cover.webp",
      "/projects/villa-03/02.living.img.webp",
      "/projects/villa-03/03.hol.img.webp",
      "/projects/villa-03/04.dormitoare.img.webp",
      "/projects/villa-03/05.dormitoare.img.webp",
      "/projects/villa-03/06.dormitoare.img.webp",
      "/projects/villa-03/07.dormitoare.img.webp",
      "/projects/villa-03/08.dormitoare.img.webp",
      "/projects/villa-03/09.dormitoare.img.webp",
      "/projects/villa-03/10.dormitoare.img.webp",
      "/projects/villa-03/11.dormitoare.img.webp",
      "/projects/villa-03/12.dormitoare.img.webp",
      "/projects/villa-03/13.dormitoare.img.webp",
      "/projects/villa-03/14.dressing.img.webp",
      "/projects/villa-03/15.dressing.img.webp",
      "/projects/villa-03/16.bai.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/villa-03/01.living.cover.webp",
        "room": "Living"
      },
      {
        "url": "/projects/villa-03/02.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/villa-03/03.hol.img.webp",
        "room": "Hol"
      },
      {
        "url": "/projects/villa-03/04.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-03/05.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-03/06.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-03/07.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-03/08.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-03/09.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-03/10.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-03/11.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-03/12.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-03/13.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-03/14.dressing.img.webp",
        "room": "Dressing"
      },
      {
        "url": "/projects/villa-03/15.dressing.img.webp",
        "room": "Dressing"
      },
      {
        "url": "/projects/villa-03/16.bai.img.webp",
        "room": "Băi"
      }
    ],
    "rooms": [
      "Living",
      "Hol",
      "Dormitoare",
      "Dressing",
      "Băi"
    ]
  },
  {
    "slug": "villa-01",
    "title": "Villa 01",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Villa 01. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/villa-01/01.bucatarii.cover.webp",
    "images": [
      "/projects/villa-01/01.bucatarii.cover.webp",
      "/projects/villa-01/02.bucatarii.img.webp",
      "/projects/villa-01/03.bucatarii.img.webp",
      "/projects/villa-01/04.bucatarii.img.webp",
      "/projects/villa-01/05.bucatarii.img.webp",
      "/projects/villa-01/06.living.img.webp",
      "/projects/villa-01/07.living.img.webp",
      "/projects/villa-01/08.living.img.webp",
      "/projects/villa-01/09.altele.img.webp",
      "/projects/villa-01/10.hol.img.webp",
      "/projects/villa-01/11.dormitoare.img.webp",
      "/projects/villa-01/12.dormitoare.img.webp",
      "/projects/villa-01/13.dormitoare.img.webp",
      "/projects/villa-01/14.dormitoare.img.webp",
      "/projects/villa-01/15.dormitoare.img.webp",
      "/projects/villa-01/16.dormitoare.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/villa-01/01.bucatarii.cover.webp",
        "room": "Bucătării"
      },
      {
        "url": "/projects/villa-01/02.bucatarii.img.webp",
        "room": "Bucătării"
      },
      {
        "url": "/projects/villa-01/03.bucatarii.img.webp",
        "room": "Bucătării"
      },
      {
        "url": "/projects/villa-01/04.bucatarii.img.webp",
        "room": "Bucătării"
      },
      {
        "url": "/projects/villa-01/05.bucatarii.img.webp",
        "room": "Bucătării"
      },
      {
        "url": "/projects/villa-01/06.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/villa-01/07.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/villa-01/08.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/villa-01/09.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-01/10.hol.img.webp",
        "room": "Hol"
      },
      {
        "url": "/projects/villa-01/11.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-01/12.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-01/13.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-01/14.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-01/15.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/villa-01/16.dormitoare.img.webp",
        "room": "Dormitoare"
      }
    ],
    "rooms": [
      "Bucătării",
      "Living",
      "Hol",
      "Dormitoare"
    ]
  },
  {
    "slug": "apartment-02",
    "title": "Apartment 02",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Apartment 02. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/apartment-02/01.dormitoare.cover.webp",
    "images": [
      "/projects/apartment-02/01.dormitoare.cover.webp",
      "/projects/apartment-02/02.dormitoare.img.webp",
      "/projects/apartment-02/03.dormitoare.img.webp",
      "/projects/apartment-02/04.dormitoare.img.webp",
      "/projects/apartment-02/05.dormitoare.img.webp",
      "/projects/apartment-02/06.dormitoare.img.webp",
      "/projects/apartment-02/07.dormitoare.img.webp",
      "/projects/apartment-02/08.living.img.webp",
      "/projects/apartment-02/09.living.img.webp",
      "/projects/apartment-02/10.living.img.webp",
      "/projects/apartment-02/11.living.img.webp",
      "/projects/apartment-02/12.living.img.webp",
      "/projects/apartment-02/13.living.img.webp",
      "/projects/apartment-02/14.living.img.webp",
      "/projects/apartment-02/15.living.img.webp",
      "/projects/apartment-02/16.living.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/apartment-02/01.dormitoare.cover.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-02/02.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-02/03.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-02/04.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-02/05.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-02/06.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-02/07.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-02/08.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-02/09.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-02/10.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-02/11.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-02/12.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-02/13.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-02/14.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-02/15.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-02/16.living.img.webp",
        "room": "Living"
      }
    ],
    "rooms": [
      "Dormitoare",
      "Living"
    ]
  },
  {
    "slug": "apartment-08",
    "title": "Apartment 08",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Apartment 08. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/apartment-08/01.dormitoare.cover.webp",
    "images": [
      "/projects/apartment-08/01.dormitoare.cover.webp",
      "/projects/apartment-08/02.dormitoare.img.webp",
      "/projects/apartment-08/03.dormitoare.img.webp",
      "/projects/apartment-08/04.dormitoare.img.webp",
      "/projects/apartment-08/05.dormitoare.img.webp",
      "/projects/apartment-08/06.dormitoare.img.webp",
      "/projects/apartment-08/07.dormitoare.img.webp",
      "/projects/apartment-08/08.dormitoare.img.webp",
      "/projects/apartment-08/09.dormitoare.img.webp",
      "/projects/apartment-08/10.hol.img.webp",
      "/projects/apartment-08/11.living.img.webp",
      "/projects/apartment-08/12.living.img.webp",
      "/projects/apartment-08/13.living.img.webp",
      "/projects/apartment-08/14.living.img.webp",
      "/projects/apartment-08/15.living.img.webp",
      "/projects/apartment-08/16.living.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/apartment-08/01.dormitoare.cover.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-08/02.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-08/03.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-08/04.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-08/05.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-08/06.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-08/07.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-08/08.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-08/09.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-08/10.hol.img.webp",
        "room": "Hol"
      },
      {
        "url": "/projects/apartment-08/11.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-08/12.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-08/13.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-08/14.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-08/15.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-08/16.living.img.webp",
        "room": "Living"
      }
    ],
    "rooms": [
      "Dormitoare",
      "Hol",
      "Living"
    ]
  },
  {
    "slug": "apartment-14",
    "title": "Apartment 14",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Apartment 14. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/apartment-14/01.altele.cover.webp",
    "images": [
      "/projects/apartment-14/01.altele.cover.webp",
      "/projects/apartment-14/02.altele.img.webp",
      "/projects/apartment-14/03.altele.img.webp",
      "/projects/apartment-14/04.altele.img.webp",
      "/projects/apartment-14/05.altele.img.webp",
      "/projects/apartment-14/06.altele.img.webp",
      "/projects/apartment-14/07.altele.img.webp",
      "/projects/apartment-14/08.altele.img.webp",
      "/projects/apartment-14/09.altele.img.webp",
      "/projects/apartment-14/10.altele.img.webp",
      "/projects/apartment-14/11.altele.img.webp",
      "/projects/apartment-14/12.altele.img.webp",
      "/projects/apartment-14/13.altele.img.webp",
      "/projects/apartment-14/14.altele.img.webp",
      "/projects/apartment-14/15.altele.img.webp",
      "/projects/apartment-14/16.altele.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/apartment-14/01.altele.cover.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-14/02.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-14/03.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-14/04.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-14/05.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-14/06.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-14/07.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-14/08.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-14/09.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-14/10.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-14/11.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-14/12.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-14/13.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-14/14.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-14/15.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-14/16.altele.img.webp",
        "room": "Altele"
      }
    ],
    "rooms": []
  },
  {
    "slug": "apartment-04",
    "title": "Apartment 04",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Apartment 04. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/apartment-04/01.altele.cover.webp",
    "images": [
      "/projects/apartment-04/01.altele.cover.webp",
      "/projects/apartment-04/02.altele.img.webp",
      "/projects/apartment-04/03.altele.img.webp",
      "/projects/apartment-04/04.altele.img.webp",
      "/projects/apartment-04/05.altele.img.webp",
      "/projects/apartment-04/06.altele.img.webp",
      "/projects/apartment-04/07.altele.img.webp",
      "/projects/apartment-04/08.altele.img.webp",
      "/projects/apartment-04/09.altele.img.webp",
      "/projects/apartment-04/10.altele.img.webp",
      "/projects/apartment-04/11.altele.img.webp",
      "/projects/apartment-04/12.altele.img.webp",
      "/projects/apartment-04/13.altele.img.webp",
      "/projects/apartment-04/14.altele.img.webp",
      "/projects/apartment-04/15.altele.img.webp",
      "/projects/apartment-04/16.altele.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/apartment-04/01.altele.cover.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-04/02.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-04/03.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-04/04.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-04/05.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-04/06.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-04/07.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-04/08.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-04/09.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-04/10.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-04/11.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-04/12.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-04/13.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-04/14.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-04/15.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-04/16.altele.img.webp",
        "room": "Altele"
      }
    ],
    "rooms": []
  },
  {
    "slug": "villa-02",
    "title": "Villa 02",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Villa 02. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/villa-02/01.altele.cover.webp",
    "images": [
      "/projects/villa-02/01.altele.cover.webp",
      "/projects/villa-02/02.altele.img.webp",
      "/projects/villa-02/03.altele.img.webp",
      "/projects/villa-02/04.altele.img.webp",
      "/projects/villa-02/05.altele.img.webp",
      "/projects/villa-02/06.altele.img.webp",
      "/projects/villa-02/07.altele.img.webp",
      "/projects/villa-02/08.altele.img.webp",
      "/projects/villa-02/09.altele.img.webp",
      "/projects/villa-02/10.altele.img.webp",
      "/projects/villa-02/11.altele.img.webp",
      "/projects/villa-02/12.altele.img.webp",
      "/projects/villa-02/13.altele.img.webp",
      "/projects/villa-02/14.altele.img.webp",
      "/projects/villa-02/15.altele.img.webp",
      "/projects/villa-02/16.altele.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/villa-02/01.altele.cover.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-02/02.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-02/03.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-02/04.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-02/05.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-02/06.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-02/07.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-02/08.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-02/09.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-02/10.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-02/11.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-02/12.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-02/13.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-02/14.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-02/15.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/villa-02/16.altele.img.webp",
        "room": "Altele"
      }
    ],
    "rooms": []
  },
  {
    "slug": "showroom-15",
    "title": "Showroom",
    "category": "Comercial",
    "description": "Proiect Moodilier — Showroom. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/showroom-15/01.altele.cover.webp",
    "images": [
      "/projects/showroom-15/01.altele.cover.webp",
      "/projects/showroom-15/02.altele.img.webp",
      "/projects/showroom-15/03.altele.img.webp",
      "/projects/showroom-15/04.altele.img.webp",
      "/projects/showroom-15/05.altele.img.webp",
      "/projects/showroom-15/06.altele.img.webp",
      "/projects/showroom-15/07.altele.img.webp",
      "/projects/showroom-15/08.altele.img.webp",
      "/projects/showroom-15/09.altele.img.webp",
      "/projects/showroom-15/10.altele.img.webp",
      "/projects/showroom-15/11.altele.img.webp",
      "/projects/showroom-15/12.altele.img.webp",
      "/projects/showroom-15/13.altele.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/showroom-15/01.altele.cover.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/showroom-15/02.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/showroom-15/03.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/showroom-15/04.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/showroom-15/05.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/showroom-15/06.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/showroom-15/07.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/showroom-15/08.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/showroom-15/09.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/showroom-15/10.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/showroom-15/11.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/showroom-15/12.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/showroom-15/13.altele.img.webp",
        "room": "Altele"
      }
    ],
    "rooms": []
  },
  {
    "slug": "apartment-03",
    "title": "Apartment 03",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Apartment 03. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/apartment-03/01.altele.cover.webp",
    "images": [
      "/projects/apartment-03/01.altele.cover.webp",
      "/projects/apartment-03/02.altele.img.webp",
      "/projects/apartment-03/03.altele.img.webp",
      "/projects/apartment-03/04.altele.img.webp",
      "/projects/apartment-03/05.altele.img.webp",
      "/projects/apartment-03/06.altele.img.webp",
      "/projects/apartment-03/07.altele.img.webp",
      "/projects/apartment-03/08.altele.img.webp",
      "/projects/apartment-03/09.altele.img.webp",
      "/projects/apartment-03/10.altele.img.webp",
      "/projects/apartment-03/11.altele.img.webp",
      "/projects/apartment-03/12.altele.img.webp",
      "/projects/apartment-03/13.altele.img.webp",
      "/projects/apartment-03/14.altele.img.webp",
      "/projects/apartment-03/15.altele.img.webp",
      "/projects/apartment-03/16.altele.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/apartment-03/01.altele.cover.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-03/02.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-03/03.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-03/04.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-03/05.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-03/06.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-03/07.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-03/08.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-03/09.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-03/10.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-03/11.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-03/12.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-03/13.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-03/14.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-03/15.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-03/16.altele.img.webp",
        "room": "Altele"
      }
    ],
    "rooms": []
  },
  {
    "slug": "apartment-05",
    "title": "Apartment 05",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Apartment 05. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/apartment-05/01.altele.cover.webp",
    "images": [
      "/projects/apartment-05/01.altele.cover.webp",
      "/projects/apartment-05/02.altele.img.webp",
      "/projects/apartment-05/03.altele.img.webp",
      "/projects/apartment-05/04.altele.img.webp",
      "/projects/apartment-05/05.altele.img.webp",
      "/projects/apartment-05/06.altele.img.webp",
      "/projects/apartment-05/07.altele.img.webp",
      "/projects/apartment-05/08.altele.img.webp",
      "/projects/apartment-05/09.altele.img.webp",
      "/projects/apartment-05/10.altele.img.webp",
      "/projects/apartment-05/11.altele.img.webp",
      "/projects/apartment-05/12.altele.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/apartment-05/01.altele.cover.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-05/02.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-05/03.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-05/04.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-05/05.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-05/06.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-05/07.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-05/08.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-05/09.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-05/10.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-05/11.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-05/12.altele.img.webp",
        "room": "Altele"
      }
    ],
    "rooms": []
  },
  {
    "slug": "apartment-07",
    "title": "Apartment 07",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Apartment 07. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/apartment-07/01.altele.cover.webp",
    "images": [
      "/projects/apartment-07/01.altele.cover.webp",
      "/projects/apartment-07/02.altele.img.webp",
      "/projects/apartment-07/03.altele.img.webp",
      "/projects/apartment-07/04.altele.img.webp",
      "/projects/apartment-07/05.altele.img.webp",
      "/projects/apartment-07/06.altele.img.webp",
      "/projects/apartment-07/07.altele.img.webp",
      "/projects/apartment-07/08.altele.img.webp",
      "/projects/apartment-07/09.altele.img.webp",
      "/projects/apartment-07/10.altele.img.webp",
      "/projects/apartment-07/11.altele.img.webp",
      "/projects/apartment-07/12.altele.img.webp",
      "/projects/apartment-07/13.altele.img.webp",
      "/projects/apartment-07/14.altele.img.webp",
      "/projects/apartment-07/15.altele.img.webp",
      "/projects/apartment-07/16.altele.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/apartment-07/01.altele.cover.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-07/02.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-07/03.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-07/04.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-07/05.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-07/06.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-07/07.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-07/08.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-07/09.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-07/10.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-07/11.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-07/12.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-07/13.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-07/14.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-07/15.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-07/16.altele.img.webp",
        "room": "Altele"
      }
    ],
    "rooms": []
  },
  {
    "slug": "apartment-10",
    "title": "Apartment 10",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Apartment 10. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/apartment-10/01.altele.cover.webp",
    "images": [
      "/projects/apartment-10/01.altele.cover.webp",
      "/projects/apartment-10/02.altele.img.webp",
      "/projects/apartment-10/03.altele.img.webp",
      "/projects/apartment-10/04.altele.img.webp",
      "/projects/apartment-10/05.altele.img.webp",
      "/projects/apartment-10/06.altele.img.webp",
      "/projects/apartment-10/07.altele.img.webp",
      "/projects/apartment-10/08.altele.img.webp",
      "/projects/apartment-10/09.altele.img.webp",
      "/projects/apartment-10/10.altele.img.webp",
      "/projects/apartment-10/11.altele.img.webp",
      "/projects/apartment-10/12.altele.img.webp",
      "/projects/apartment-10/13.altele.img.webp",
      "/projects/apartment-10/14.altele.img.webp",
      "/projects/apartment-10/15.altele.img.webp",
      "/projects/apartment-10/16.altele.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/apartment-10/01.altele.cover.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-10/02.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-10/03.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-10/04.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-10/05.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-10/06.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-10/07.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-10/08.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-10/09.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-10/10.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-10/11.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-10/12.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-10/13.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-10/14.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-10/15.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-10/16.altele.img.webp",
        "room": "Altele"
      }
    ],
    "rooms": []
  },
  {
    "slug": "apartment-11",
    "title": "Apartment 11",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Apartment 11. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/apartment-11/01.altele.cover.webp",
    "images": [
      "/projects/apartment-11/01.altele.cover.webp",
      "/projects/apartment-11/02.altele.img.webp",
      "/projects/apartment-11/03.altele.img.webp",
      "/projects/apartment-11/04.altele.img.webp",
      "/projects/apartment-11/05.altele.img.webp",
      "/projects/apartment-11/06.altele.img.webp",
      "/projects/apartment-11/07.altele.img.webp",
      "/projects/apartment-11/08.altele.img.webp",
      "/projects/apartment-11/09.altele.img.webp",
      "/projects/apartment-11/10.altele.img.webp",
      "/projects/apartment-11/11.altele.img.webp",
      "/projects/apartment-11/12.altele.img.webp",
      "/projects/apartment-11/13.altele.img.webp",
      "/projects/apartment-11/14.altele.img.webp",
      "/projects/apartment-11/15.altele.img.webp",
      "/projects/apartment-11/16.altele.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/apartment-11/01.altele.cover.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-11/02.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-11/03.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-11/04.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-11/05.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-11/06.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-11/07.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-11/08.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-11/09.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-11/10.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-11/11.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-11/12.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-11/13.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-11/14.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-11/15.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-11/16.altele.img.webp",
        "room": "Altele"
      }
    ],
    "rooms": []
  },
  {
    "slug": "apartment-09",
    "title": "Apartment 09",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Apartment 09. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/apartment-09/01.bucatarii.cover.webp",
    "images": [
      "/projects/apartment-09/01.bucatarii.cover.webp",
      "/projects/apartment-09/02.bucatarii.img.webp",
      "/projects/apartment-09/03.bucatarii.img.webp",
      "/projects/apartment-09/04.bucatarii.img.webp",
      "/projects/apartment-09/05.dormitoare.img.webp",
      "/projects/apartment-09/06.dormitoare.img.webp",
      "/projects/apartment-09/07.dormitoare.img.webp",
      "/projects/apartment-09/08.dormitoare.img.webp",
      "/projects/apartment-09/09.dormitoare.img.webp",
      "/projects/apartment-09/10.dormitoare.img.webp",
      "/projects/apartment-09/11.dormitoare.img.webp",
      "/projects/apartment-09/12.living.img.webp",
      "/projects/apartment-09/13.living.img.webp",
      "/projects/apartment-09/14.living.img.webp",
      "/projects/apartment-09/15.living.img.webp",
      "/projects/apartment-09/16.living.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/apartment-09/01.bucatarii.cover.webp",
        "room": "Bucătării"
      },
      {
        "url": "/projects/apartment-09/02.bucatarii.img.webp",
        "room": "Bucătării"
      },
      {
        "url": "/projects/apartment-09/03.bucatarii.img.webp",
        "room": "Bucătării"
      },
      {
        "url": "/projects/apartment-09/04.bucatarii.img.webp",
        "room": "Bucătării"
      },
      {
        "url": "/projects/apartment-09/05.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-09/06.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-09/07.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-09/08.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-09/09.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-09/10.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-09/11.dormitoare.img.webp",
        "room": "Dormitoare"
      },
      {
        "url": "/projects/apartment-09/12.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-09/13.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-09/14.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-09/15.living.img.webp",
        "room": "Living"
      },
      {
        "url": "/projects/apartment-09/16.living.img.webp",
        "room": "Living"
      }
    ],
    "rooms": [
      "Bucătării",
      "Dormitoare",
      "Living"
    ]
  },
  {
    "slug": "apartment-06",
    "title": "Apartment 06",
    "category": "Rezidențial",
    "description": "Proiect Moodilier — Apartment 06. Mobilier premium la comandă, executat în atelierul propriu.",
    "coverImage": "/projects/apartment-06/01.altele.cover.webp",
    "images": [
      "/projects/apartment-06/01.altele.cover.webp",
      "/projects/apartment-06/02.altele.img.webp",
      "/projects/apartment-06/03.altele.img.webp",
      "/projects/apartment-06/04.altele.img.webp",
      "/projects/apartment-06/05.altele.img.webp",
      "/projects/apartment-06/06.altele.img.webp",
      "/projects/apartment-06/07.altele.img.webp",
      "/projects/apartment-06/08.altele.img.webp",
      "/projects/apartment-06/09.altele.img.webp",
      "/projects/apartment-06/10.altele.img.webp",
      "/projects/apartment-06/11.altele.img.webp",
      "/projects/apartment-06/12.altele.img.webp",
      "/projects/apartment-06/13.altele.img.webp",
      "/projects/apartment-06/14.altele.img.webp",
      "/projects/apartment-06/15.altele.img.webp",
      "/projects/apartment-06/16.altele.img.webp"
    ],
    "gallery": [
      {
        "url": "/projects/apartment-06/01.altele.cover.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-06/02.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-06/03.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-06/04.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-06/05.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-06/06.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-06/07.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-06/08.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-06/09.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-06/10.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-06/11.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-06/12.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-06/13.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-06/14.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-06/15.altele.img.webp",
        "room": "Altele"
      },
      {
        "url": "/projects/apartment-06/16.altele.img.webp",
        "room": "Altele"
      }
    ],
    "rooms": []
  }
];
